[tools]
aws = "latest"
bun = "latest"
ffmpeg = "latest"
firebase = "latest"
java = "openjdk-23.0.2"
node = "latest"
pnpm = "latest"
python = "latest"
rust = "latest"
tmux = "latest"
uv = "latest"
yarn = "latest"

[settings]
idiomatic_version_file_enable_tools = []
